version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend-first-class  
    ports:
      - "8080:8080"  
    restart: always

    volumes:
      - ../Firstclassflight:/app
      - /app/node_modules
